marttiphpbb_calendarweekview_page_controller:
    pattern: /calendar/{year}/{month}
    defaults: { _controller: marttiphpbb.calendarweekview.controller:page }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$

marttiphpbb_calendarweekview_redirect_to_year_controller:
    pattern: /calendar/{year}
    defaults: { _controller: marttiphpbb.calendarweekview.redirect_controller:to_year }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$

marttiphpbb_calendarweekview_redirect_to_now_controller:
    pattern: /calendar
    defaults: { _controller: marttiphpbb.calendarweekview.redirect_controller:to_now }
    requirements:
        _method: GET
