services:
    marttiphpbb.calendarweekview.listener:
        class: marttiphpbb\calendarweekview\event\listener
        tags:
            - { name: event.listener }

    marttiphpbb.calendarweekview.store:
        class: marttiphpbb\calendarweekview\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.calendarweekview.user_today:
        class: marttiphpbb\calendarweekview\service\user_today
        arguments:
            - '@user'
