services:
    marttiphpbb.calendarweekview.listener:
        class: marttiphpbb\calendarweekview\event\listener
        tags:
            - { name: event.listener }

    marttiphpbb.calendarweekview.render_listener:
        class: marttiphpbb\calendarweekview\event\render_listener
        arguments:
            - '@auth'
            - '@marttiphpbb.calendarweekview.render'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarweekview.store:
        class: marttiphpbb\calendarweekview\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.calendarweekview.user_today:
        class: marttiphpbb\calendarweekview\service\user_today
        arguments:
            - '@user'

    marttiphpbb.calendarweekview.user_time:
        class: marttiphpbb\calendarweekview\service\user_time
        arguments:
            - '@user'
            - '@marttiphpbb.calendarweekview.store'

    marttiphpbb.calendarweekview.render:
        class: marttiphpbb\calendarweekview\service\render
        arguments:
            - '@dispatcher'
            - '%core.php_ext%'
            - '@language'
            - '%core.root_path%'
            - '@marttiphpbb.calendarweekview.store'
            - '@marttiphpbb.calendarweekview.user_today'
            - '@marttiphpbb.calendarweekview.user_time'
