services:
    marttiphpbb.calendarinlineview.listener:
        class: marttiphpbb\calendarinlineview\event\listener
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinlineview.render_listener:
        class: marttiphpbb\calendarinlineview\event\render_listener
        arguments:
            - '@auth'
            - '@marttiphpbb.calendarinlineview.render'
        tags:
            - { name: event.listener }

    marttiphpbb.calendarinlineview.store:
        class: marttiphpbb\calendarinlineview\service\store
        arguments:
            - '@config_text'
            - '@cache.driver'

    marttiphpbb.calendarinlineview.user_today:
        class: marttiphpbb\calendarinlineview\service\user_today
        arguments:
            - '@user'

    marttiphpbb.calendarinlineview.user_time:
        class: marttiphpbb\calendarinlineview\service\user_time
        arguments:
            - '@user'
            - '@marttiphpbb.calendarinlineview.store'

    marttiphpbb.calendarinlineview.render:
        class: marttiphpbb\calendarinlineview\service\render
        arguments:
            - '@dispatcher'
            - '%core.php_ext%'
            - '@language'
            - '%core.root_path%'
            - '@marttiphpbb.calendarinlineview.store'
            - '@marttiphpbb.calendarinlineview.user_today'
            - '@marttiphpbb.calendarinlineview.user_time'
